### ISSUE TITLE
Import error with numpy v1.23+

### ISSUE THREAD

**Issue by cameronrulten** [sstcam/sstcam-simulation#10]
Import Camera  fails with the following error:

```AttributeError: module 'numpy' has no attribute 'asscalar'```

It looks like NumPy has had numpy.asscalar() deprecated since v1.16 and finally removed in v1.23.

In the short-term the environment.yml file needs to limit the numpy version <v1.23 , or better, the necessary changes need to be made to ensure numpy v1.23+ compatibility.

Error trace attached

[sstcam-simulation-numpy-error.txt](https://github.com/sstcam/sstcam-simulation/files/10839207/sstcam-simulation-numpy-error.txt)

**Comment by watsonjj** [comment]
Should be addressed now. Please reopen if there is still a problem/
