### ISSUE TITLE
pip warning in environment.yml

### ISSUE THREAD

**Issue by akira-okumura** [sstcam/sstcam-simulation#4]
```
(base) $ conda env create -f environment.yml
```
emits never-ending Waning messages in conda 4.10.1 on macOS 11.4. It is not literarily just a warning but a blocker.
```
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
Warning: you have pip-installed dependencies in your environment file, but you do not list pip itself as one of your conda dependencies.  Conda may not use the correct pip to install your packages, and they may end up in the wrong place.  Please add an explicit pip dependency.  I'm adding one for you, but still nagging you.
...
```

This is due to that recent Anaconda distributions do not include `pip` by default, and thus `environment.yml` needs to add `pip` explicitly. Changing the YAML file fixes it.
```
  - eventio>=1.4.1
  - pip
  - pip:
      - "--editable=git+https://github.com/sstcam/CHECLabPy#egg=CHECLabPy"
```

**Comment by akira-okumura** [comment]
I assigned @Sunghyunbang in addition to @watsonjj because this simple update looks to be a good Git practice for him.

**Comment by akira-okumura** [comment]
The same endless warning happens on CentOS 8 with the same conda version of 4.10.1.

**Comment by watsonjj** [comment]
I agree with the required solution - pip should be added to the environment.yml

**Comment by watsonjj** [comment]
I added pip to the environment.yml in https://github.com/sstcam/sstcam-simulation/commit/1a4815d29002b30a02fd38c81978e96ec84ad8cf
