### ISSUE TITLE
Cython dependency missing

### ISSUE THREAD

**Issue by RichardWhite109** [sstcam/sstcam-simulation#8]
`python setup.py develop` fails following default setup instructions in README. Dependency on cython seems to be missing (easily fixed by hand with `conda install cython` but could be added to the environment setup.

**Comment by watsonjj** [comment]
This seems to be due to changes in recent versions of pyeventio. I have created an isssue: https://github.com/cta-observatory/pyeventio/issues/239

**Comment by maxnoe** [comment]
No, this is because you should not use `python setup.py install`. Please use `pip install [-e] .` with a not-to-outdated pip, that properly takes into account build time depedencies.

**Comment by watsonjj** [comment]
Thanks @maxnoe. I have updated the CI and instructions to use `pip install [-e] .`
